//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoridgeServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingLog
    {
        public int Id { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string CustomerOrgNo { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerAddress { get; set; }
        public string VehicleRegNo { get; set; }
        public string CompanyName { get; set; }
        public string BookingMessage { get; set; }
        public int ResourceId { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
