//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoridgeServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyMoridgeServerModelContainer1 : DbContext
    {
        public MyMoridgeServerModelContainer1()
            : base("name=MyMoridgeServerModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustomerVehicle> CustomerVehicles { get; set; }
        public DbSet<ErrorLog> ErrorLogSet { get; set; }
        public DbSet<BookingLog> BookingLogs { get; set; }
        public DbSet<Resource> Resources { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<EmailLog> EmailLogs { get; set; }
        public DbSet<InvitationVoucher> InvitationVouchers { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Payment> Payments { get; set; }
    }
}
