//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoridgeServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string TransId { get; set; }
        public string TransType { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public string PaymentInstrumentType { get; set; }
        public int BookingLogId { get; set; }
    
        public virtual BookingLog BookingLog { get; set; }
    }
}
