//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoridgeServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.BookingLog = new HashSet<BookingLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CalendarEmail { get; set; }
        public string CalendarServiceAccountEmail { get; set; }
        public int MaxBookingsBeforeLunch { get; set; }
        public int MaxBookingsAfterLunch { get; set; }
        public int DaysBeforeBooking { get; set; }
        public int BookingPriority { get; set; }
    
        public virtual ICollection<BookingLog> BookingLog { get; set; }
    }
}
